/*
FORCESNLPsolver_final : A fast customized optimization solver.

Copyright (C) 2013-2022 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCESPRO v6.0.1 on Friday, January 6, 2023 at 7:45:02 AM */
#ifndef FORCESNLPsolver_final_H
#define FORCESNLPsolver_final_H

#ifndef SOLVER_STDIO_H
#define SOLVER_STDIO_H
#include <stdio.h>
#endif
#ifndef SOLVER_STRING_H
#define SOLVER_STRING_H
#include <string.h>
#endif


#ifndef SOLVER_STANDARD_TYPES
#define SOLVER_STANDARD_TYPES

typedef signed char solver_int8_signed;
typedef unsigned char solver_int8_unsigned;
typedef char solver_int8_default;
typedef signed short int solver_int16_signed;
typedef unsigned short int solver_int16_unsigned;
typedef short int solver_int16_default;
typedef signed int solver_int32_signed;
typedef unsigned int solver_int32_unsigned;
typedef int solver_int32_default;
typedef signed long long int solver_int64_signed;
typedef unsigned long long int solver_int64_unsigned;
typedef long long int solver_int64_default;

#endif


/* DATA TYPE ------------------------------------------------------------*/
typedef double FORCESNLPsolver_final_float;
typedef double FORCESNLPsolver_final_ldl_s_float;
typedef double FORCESNLPsolver_final_ldl_r_float;
typedef double FORCESNLPsolver_final_callback_float;

typedef double FORCESNLPsolver_finalinterface_float;

/* SOLVER SETTINGS ------------------------------------------------------*/

/* MISRA-C compliance */
#ifndef MISRA_C_FORCESNLPsolver_final
#define MISRA_C_FORCESNLPsolver_final (0)
#endif

/* restrict code */
#ifndef RESTRICT_CODE_FORCESNLPsolver_final
#define RESTRICT_CODE_FORCESNLPsolver_final (0)
#endif

/* print level */
#ifndef SET_PRINTLEVEL_FORCESNLPsolver_final
#define SET_PRINTLEVEL_FORCESNLPsolver_final    (1)
#endif

/* timing */
#ifndef SET_TIMING_FORCESNLPsolver_final
#define SET_TIMING_FORCESNLPsolver_final    (1)
#endif

/* Numeric Warnings */
/* #define PRINTNUMERICALWARNINGS */

/* maximum number of iterations  */
#define SET_MAXIT_FORCESNLPsolver_final			(200)	

/* scaling factor of line search (FTB rule) */
#define SET_FLS_SCALE_FORCESNLPsolver_final		(FORCESNLPsolver_final_float)(0.99)      

/* maximum number of supported elements in the filter */
#define MAX_FILTER_SIZE_FORCESNLPsolver_final	(200) 

/* maximum number of supported elements in the filter */
#define MAX_SOC_IT_FORCESNLPsolver_final			(4) 

/* desired relative duality gap */
#define SET_ACC_RDGAP_FORCESNLPsolver_final		(FORCESNLPsolver_final_float)(0.0001)

/* desired maximum residual on equality constraints */
#define SET_ACC_RESEQ_FORCESNLPsolver_final		(FORCESNLPsolver_final_float)(1E-06)

/* desired maximum residual on inequality constraints */
#define SET_ACC_RESINEQ_FORCESNLPsolver_final	(FORCESNLPsolver_final_float)(1E-06)

/* desired maximum violation of complementarity */
#define SET_ACC_KKTCOMPL_FORCESNLPsolver_final	(FORCESNLPsolver_final_float)(1E-06)


/* SOLVER RETURN CODES----------------------------------------------------------*/
/* solver has converged within desired accuracy */
#define OPTIMAL_FORCESNLPsolver_final      (1)

/* maximum number of iterations has been reached */
#define MAXITREACHED_FORCESNLPsolver_final (0)

/* solver has stopped due to a timeout */
#define TIMEOUT_FORCESNLPsolver_final   (2)

/* solver stopped externally */
#define EXIT_EXTERNAL_FORCESNLPsolver_final (3)

/* wrong number of inequalities error */
#define INVALID_NUM_INEQ_ERROR_FORCESNLPsolver_final  (-4)

/* factorization error */
#define FACTORIZATION_ERROR_FORCESNLPsolver_final   (-5)

/* NaN encountered in function evaluations */
#define BADFUNCEVAL_FORCESNLPsolver_final  (-6)

/* no progress in method possible */
#define NOPROGRESS_FORCESNLPsolver_final   (-7)

/* regularization error */
#define REGULARIZATION_ERROR_FORCESNLPsolver_final   (-9)

/* invalid values in parameters */
#define PARAM_VALUE_ERROR_FORCESNLPsolver_final   (-11)

/* too small timeout given */
#define INVALID_TIMEOUT_FORCESNLPsolver_final   (-12)

/* thread error */
#define THREAD_FAILURE_FORCESNLPsolver_final  (-98)

/* locking mechanism error */
#define LOCK_FAILURE_FORCESNLPsolver_final  (-99)

/* licensing error - solver not valid on this machine */
#define LICENSE_ERROR_FORCESNLPsolver_final  (-100)

/* Insufficient number of internal memory instances.
 * Increase codeoptions.max_num_mem. */
#define MEMORY_INVALID_FORCESNLPsolver_final (-101)
/* Number of threads larger than specified.
 * Increase codeoptions.nlp.max_num_threads. */
#define NUMTHREADS_INVALID_FORCESNLPsolver_final (-102)

/* INTEGRATORS RETURN CODE ------------*/
/* Integrator ran successfully */
#define INTEGRATOR_SUCCESS (11)
/* Number of steps set by user exceeds maximum number of steps allowed */
#define INTEGRATOR_MAXSTEPS_EXCEEDED (12)


/* MEMORY STRUCT --------------------------------------------------------*/
typedef struct FORCESNLPsolver_final_mem FORCESNLPsolver_final_mem;
#ifdef __cplusplus
extern "C" {
#endif
/* MEMORY STRUCT --------------------------------------------------------*/
extern FORCESNLPsolver_final_mem * FORCESNLPsolver_final_external_mem(void * mem_ptr, solver_int32_unsigned i_mem, size_t mem_size);
extern size_t FORCESNLPsolver_final_get_mem_size( void );
extern size_t FORCESNLPsolver_final_get_const_size( void );
#ifdef __cplusplus
}
#endif

/* PARAMETERS -----------------------------------------------------------*/
/* fill this with data before calling the solver! */
typedef struct
{
    /* vector of size 9 */
    FORCESNLPsolver_final_float xinit[9];

    /* vector of size 340 */
    FORCESNLPsolver_final_float x0[340];

    /* vector of size 2600 */
    FORCESNLPsolver_final_float all_parameters[2600];

    /* scalar */
    solver_int32_unsigned num_of_threads;


} FORCESNLPsolver_final_params;


/* OUTPUTS --------------------------------------------------------------*/
/* the desired variables are put here by the solver */
typedef struct
{
    /* column vector of length 17 */
    FORCESNLPsolver_final_float x01[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x02[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x03[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x04[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x05[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x06[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x07[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x08[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x09[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x10[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x11[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x12[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x13[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x14[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x15[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x16[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x17[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x18[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x19[17];

    /* column vector of length 17 */
    FORCESNLPsolver_final_float x20[17];


} FORCESNLPsolver_final_output;


/* SOLVER INFO ----------------------------------------------------------*/
/* diagnostic data from last interior point step */
typedef struct
{
    /* scalar: iteration number */
    solver_int32_default it;

    /* scalar: number of iterations needed to optimality (branch-and-bound) */
    solver_int32_default it2opt;

    /* scalar: inf-norm of equality constraint residuals */
    FORCESNLPsolver_final_float res_eq;

    /* scalar: inf-norm of inequality constraint residuals */
    FORCESNLPsolver_final_float res_ineq;

    /* scalar: norm of stationarity condition */
    FORCESNLPsolver_final_float rsnorm;

    /* scalar: max of all complementarity violations */
    FORCESNLPsolver_final_float rcompnorm;

    /* scalar: primal objective */
    FORCESNLPsolver_final_float pobj;

    /* scalar: dual objective */
    FORCESNLPsolver_final_float dobj;

    /* scalar: duality gap := pobj - dobj */
    FORCESNLPsolver_final_float dgap;

    /* scalar: relative duality gap := |dgap / pobj | */
    FORCESNLPsolver_final_float rdgap;

    /* scalar: duality measure */
    FORCESNLPsolver_final_float mu;

    /* scalar: duality measure (after affine step) */
    FORCESNLPsolver_final_float mu_aff;

    /* scalar: centering parameter */
    FORCESNLPsolver_final_float sigma;

    /* scalar: number of backtracking line search steps (affine direction) */
    solver_int32_default lsit_aff;

    /* scalar: number of backtracking line search steps (combined direction) */
    solver_int32_default lsit_cc;

    /* scalar: step size (affine direction) */
    FORCESNLPsolver_final_float step_aff;

    /* scalar: step size (combined direction) */
    FORCESNLPsolver_final_float step_cc;

    /* scalar: total solve time */
    FORCESNLPsolver_final_float solvetime;

    /* scalar: time spent in function evaluations */
    FORCESNLPsolver_final_float fevalstime;

    /* column vector of length 8: solver ID of FORCESPRO solver */
    solver_int32_default solver_id[8];




} FORCESNLPsolver_final_info;







/* SOLVER FUNCTION DEFINITION -------------------------------------------*/
/* Time of Solver Generation: (UTC) Friday, January 6, 2023 7:45:04 AM */
/* User License expires on: (UTC) Sunday, June 25, 2023 10:00:00 PM (approx.) (at the time of code generation) */
/* Solver Static License expires on: (UTC) Sunday, June 25, 2023 10:00:00 PM (approx.) */
/* Solver Id: f5b7d1dd-bdc6-4ba2-ac64-84e7303fa947 */
/* examine exitflag before using the result! */
#ifdef __cplusplus
extern "C" {
#endif		

typedef solver_int32_default (*FORCESNLPsolver_final_extfunc)(FORCESNLPsolver_final_float* x, FORCESNLPsolver_final_float* y, FORCESNLPsolver_final_float* lambda, FORCESNLPsolver_final_float* params, FORCESNLPsolver_final_float* pobj, FORCESNLPsolver_final_float* g, FORCESNLPsolver_final_float* c, FORCESNLPsolver_final_float* Jeq, FORCESNLPsolver_final_float* h, FORCESNLPsolver_final_float* Jineq, FORCESNLPsolver_final_float* H, solver_int32_default stage, solver_int32_default iterations, solver_int32_default threadID);

extern solver_int32_default FORCESNLPsolver_final_solve(FORCESNLPsolver_final_params *params, FORCESNLPsolver_final_output *output, FORCESNLPsolver_final_info *info, FORCESNLPsolver_final_mem *mem, FILE *fs, FORCESNLPsolver_final_extfunc evalextfunctions_FORCESNLPsolver_final);











#ifdef __cplusplus
}
#endif

#endif
